/* ============================================================================
   Configuration
   ============================================================================

   --- Password (optional) ---------------------------------------------------
   Leave AUTH blank and the app is open to anyone with the link.
   To require a shared password, open  setup-password.html , type a password,
   and paste the generated AUTH block (and, if you use sync, the encrypted key)
   here. Full steps in PASSWORD_SETUP.md.

   --- Live team sync (optional) ---------------------------------------------
   Leave SUPABASE_* blank for single-browser mode. To share one live dataset,
   fill these in — see SUPABASE_SETUP.md. If you also use a password, protect
   the key by pasting the encrypted version into SUPABASE_ANON_KEY_ENC (from
   setup-password.html) and leaving SUPABASE_ANON_KEY blank.
   ============================================================================ */
window.APP_CONFIG = {
  // Supabase (live sync) — see SUPABASE_SETUP.md
  SUPABASE_URL: "",
  SUPABASE_ANON_KEY: "",       // plaintext key (fine if you have no password)
  SUPABASE_ANON_KEY_ENC: "",   // password-encrypted key (from setup-password.html)
  TABLE: "checklist",

  // Password gate — generated by setup-password.html. Blank = no password.
  AUTH: {
    salt: "VAh7K48WUvh9kRoPfE2PyQ==",
    check: "oRWSc3YMfGvaZijxk0A/6bbLKMaNTfipI0yOiEFVADUxcrctvSBBS11K8KoTiGnPHByBfPc=",
  },
};
